### ISSUE TITLE
Lein new +option support

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot-new#5]
It is so great that you are going to implement this, I use templates extensively.

In [tenzing](https://github.com/martinklepsch/tenzing#create-a-project) and many other `lein` templates, you can specify additional options to the `new` task, usually prefixed by `+` (I guess it is just a convention) when they add some feature.

It would be great if `boot-new` supported them as well.

Cheers

**Comment by seancorfield** [comment]
Lein new uses -- to delineate arguments passed to the template. Boot new uses the -a / --args option to specify arguments that get passed to the template. 

So `boot new -t tenzing -a arg1 -a arg2 -n myapp` should. 

Check `boot new -h` for other options. Basically every option supported by lein new is supported but a few have different names or syntax due to Boot task option handling.

**Comment by arichiardi** [comment]
I tried but it gives me back weird things:

```
boot -d seancorfield/boot-new new -t tenzing -n myapp -a +divshot -a +test
Error reading profiles.clj from ~/.lein
Could not find template tenzing on the classpath.
```

Am I doing it right?

**Comment by seancorfield** [comment]
Ah, ok, that might be some of the residual Leiningen code that Boot new uses to find and load templates. I haven't tried Boot new on a system that doesn't have a legacy ~/.lein/profiles.clj so try creating one of those. Perhaps empty, perhaps containing just {}

**Comment by arichiardi** [comment]
The problem is that I have it already :smile:

**Comment by seancorfield** [comment]
Can you share what's in that file (given that it says it has a problem reading it)?

**Comment by seancorfield** [comment]
I tested this locally and the following command works:

```
boot -d seancorfield/boot-new:0.2.0-SNAPSHOT new -t tenzing -n tenztest -a +divshot -a +test
Generating fresh 'lein new' tenzing project.
```

So I'd say there's something in your `~/.lein/profiles.clj` that is causing a failure.

**Comment by seancorfield** [comment]
BTW, that produces this so it seems to be working:

```
> tree tenztest
tenztest
|____.gitignore
|____boot.properties
|____build.boot
|____divshot.json
|____resources
| |____index.html
| |____js
| | |____app.cljs.edn
|____src
| |____cljs
| | |____tenztest
| | | |____app.cljs
|____test
| |____cljs
| | |____tenztest
| | | |____app_test.cljs
```

**Comment by arichiardi** [comment]
Should we reopen this?

My profile.clj:

```
{:user
 {:plugins [[lein-kibit "0.1.2"]
            [com.jakemccrary/lein-test-refresh "0.11.0"]
            [refactor-nrepl "2.0.0-SNAPSHOT"]
            [cider/cider-nrepl "0.11.0-SNAPSHOT"]
            [venantius/ultra "0.4.0"]]
  :dependencies [[org.clojure/tools.nrepl "0.2.11"]
                 [acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]
                 [org.clojure/tools.namespace "0.2.11"]
                 [leiningen #=(leiningen.core.main/leiningen-version)]
                 [io.aviso/pretty "0.1.19"]
                 [spyscope "0.1.4"]
                 [alembic "0.3.2"]
                 [im.chit/vinyasa "0.4.2"]]
  :ultra {:color-scheme :solarized_dark}
  :repl-options  {:prompt (fn [ns]
                            (str "\033[1;32m"
                                 (let [nss (clojure.string/split ns #"[.]")]
                                   (if (= 1 (count nss))
                                     (first nss)
                                     (str "-." (clojure.string/join "." (drop 1 nss)))))
                                 "=>" "\033[0m "))}

  :resource-paths ["/usr/local/share/doc/java/docs/api/"]
  :figwheel {:nrepl-port 5088
             :open-file-command "open-emacs"
             ;; Load CIDER, refactor-nrepl and piggieback middleware
             :nrepl-middleware ["cider.nrepl/cider-middleware"
                                "refactor-nrepl.middleware/wrap-refactor"
                                "cemerick.piggieback/wrap-cljs-repl"]}
  :injections [(require 'spyscope.core)
               (require '[vinyasa.inject :as inject])
               (require 'io.aviso.repl)
               (inject/in ;; the default injected namespace is `.`

                ;; note that `:refer, :all and :exclude can be used
                [vinyasa.inject :refer [inject [in inject-in]]]
                [vinyasa.lein :exclude [*project*]]

                ;; imports all functions in vinyasa.pull
                [alembic.still [distill pull]]

                ;; same as [cemerick.pomegranate :refer [add-classpath get-classpath resources]]
                [cemerick.pomegranate add-classpath get-classpath resources]

                ;; inject into clojure.core
                clojure.core
                [vinyasa.reflection .> .? .* .% .%> .& .>ns .>var]

                ;; inject into clojure.core with prefix
                clojure.core >
                [clojure.pprint pprint]
                [clojure.java.shell sh])]
  }
 :android-common {:dependencies [[cider/cider-nrepl "0.11.0-SNAPSHOT"]]
                  :android {:sdk-path "/usr/local/share/android-sdk"
                            :aot-exclude-ns ["cider.nrepl.middleware.util.java.parser"
                                             "cider.nrepl" "cider-nrepl.plugin"]}}
 :test-refresh {:growl true}}
```

**Comment by seancorfield** [comment]
Yikes, that's a crazy default set of profiles!

Given that I'm reworking Boot new to avoid user profiles completely, I expect this problem to just go away in 0.2.0 and since this works for me with a simpler profiles file, I'm not reopening this. 

I will, however, out of curiosity try with your profile in place and see if there's any obvious issue with 0.1.0.

**Comment by arichiardi** [comment]
I tried with `-vv` and:

```
Error reading profiles.clj from /home/kapitan/.lein
Error reading profiles.clj from /home/kapitan/.lein

Could not load template, failed with: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
clojure.lang.ExceptionInfo: boot.App$Exit: 1 {:file "/tmp/boot.user5831892775465117033.clj", :line 25}
    at clojure.core$ex_info.invoke(core.clj:4593)
    at boot.main$_main$fn__1272.invoke(main.clj:199)
    at boot.main$_main.invoke(main.clj:192)
    at clojure.lang.Var.invoke(Var.java:394)
    at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:159)
    at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:150)
    at boot.App.runBoot(App.java:390)
    at boot.App.main(App.java:467)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at Boot.main(Boot.java:258)
Caused by: java.util.concurrent.ExecutionException: boot.App$Exit: 1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at clojure.core$deref_future.invoke(core.clj:2186)
    at clojure.core$future_call$reify__6736.deref(core.clj:6683)
    at clojure.core$deref.invoke(core.clj:2206)
    at boot.core$boot.doInvoke(core.clj:801)
    at clojure.lang.RestFn.invoke(RestFn.java:703)
    at boot.user$eval2961.invoke(boot.user5831892775465117033.clj:45)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.lang.RT$3.invoke(RT.java:319)
    at boot.main$_main$fn__1272.invoke(main.clj:192)
    ... 11 more
Caused by: boot.App$Exit: 1
    at boot.new$resolve_remote_template.invoke(new.clj:63)
    at boot.new$resolve_template$fn__2865.invoke(new.clj:72)
    at boot.new$resolve_template.invoke(new.clj:69)
    at boot.new$create.invoke(new.clj:103)
    at boot.new$eval2883$fn__2884$fn__2890$fn__2891$fn__2894.invoke(new.clj:145)
    at boot.new$eval2883$fn__2884$fn__2890$fn__2891.invoke(new.clj:139)
    at boot.core$run_tasks.invoke(core.clj:794)
    at boot.core$boot$fn__904.invoke(core.clj:804)
    at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by seancorfield** [comment]
There's no debugging inside Boot new itself which is what I'll need to add in order to see what it doesn't like about your profiles.clj file.

**Comment by arichiardi** [comment]
It looks like it is passing some `nil` somewhere, but as you said, it makes sense to work without user profiles whatsoever, so I will be waiting for that patch, thanks a lot!

**Comment by seancorfield** [comment]
That stack trace is all coming from Boot new call boot.util/exit-error _after_ it has already failed to read something in your profiles.clj and is not relevant to the issue at hand here. Be patient. I'll look at this later today.

**Comment by arichiardi** [comment]
Right, I will be, no rush :+1:

**Comment by seancorfield** [comment]
After adding some debugging, I can see the exception is coming from deep within the leiningen-core library that Boot new is leaning on for some functionality (even after removing the code that attempted to read the user profiles). A workaround, until I remove dependence on leiningen-core is to set `LEIN_VERSION=2.5.3` as an environment variable when invoking Boot new. Ugly, but it works.

I'll continue working on removing the dependency on leiningen-core -- and at least I have a good test case for that now :)

**Comment by seancorfield** [comment]
OK, try `seancorfield/boot-new:0.2.0-SNAPSHOT` now. That no longer depends on Leiningen at all to create the template (although the template itself may still rely on some parts of `leiningen-core` which is still added as a dependency). I can now create the Tenzing-based project without the environment variable workaround, using your `profiles.clj` file.

**Comment by arichiardi** [comment]
I can't for some reason, but if it works on your end it's fine (maybe you did not push on clojars last SNAPSHOT?)
I am doing:
`boot -d seancorfield/boot-new:0.2.0-SNAPSHOT new -t tenzing -n myapp -a +divshot -a +test`

**Comment by seancorfield** [comment]
```
(! 732)-> cp ~/Desktop/bad_profiles.clj ~/.lein/profiles.clj 

Mon Jan 18 17:42:19
(sean)-(jobs:0)-(~/clojure/boot-tests)
(! 733)-> boot -d seancorfield/boot-new:0.2.0-SNAPSHOT new -t tenzing -n myapp -a +divshot -a +test
Retrieving boot-new-0.2.0-20160119.014206-8.jar from https://clojars.org/repo/
Generating fresh 'lein new' tenzing project.

Mon Jan 18 17:42:36
(sean)-(jobs:0)-(~/clojure/boot-tests)
(! 734)-> tree myapp
myapp
|____.gitignore
|____boot.properties
|____build.boot
|____divshot.json
|____resources
| |____index.html
| |____js
| | |____app.cljs.edn
|____src
| |____cljs
| | |____myapp
| | | |____app.cljs
|____test
| |____cljs
| | |____myapp
| | | |____app_test.cljs
```

Latest 0.2.0 SNAPSHOT (you can even see it download that), your `profiles.clj`, that exact command. Nothing in Boot new itself relies on Leiningen now. The Tenzing template itself still relies on Leiningen (`leiningen-core`) which is still a dependency in Boot new.

**Comment by arichiardi** [comment]
I manually removed your artefact from my `.m2/repository` and it now works!

**Comment by seancorfield** [comment]
Ah, you might be only checking for new snapshots once a day and I've pushed several builds today as I chipped away at the Leiningen dependencies. Glad it's working now!
